### ISSUE TITLE
Diagonal sudoku?

### ISSUE THREAD

**Issue by vsevjednom-cz** [pocketjoso/sudokuJS#6]
Hi,
your code is amazing, thank you for this! But is also possible to solve diagonal sudoku?

**Comment by vsevjednom-cz** [comment]
Or there's maybe some another problem. Try this:
```
var board = [
	, ,3,6, ,5,7, , 
	, , , ,9, ,1, , , 
	,7, , , , , , , ,4
	,9,6, , , , , ,8,3
	, , , , , , , , ,
	,4,8, , , , , ,1,9
	,6, , , , , , , ,5
	, , , ,5, ,7, , , 
	, , ,2,1, ,6,9, ,undefined
]
```
Your solver cannot solve it but other solvers yes. I don't know why.

**Comment by pocketjoso** [comment]
Hi!

The solver is not capable of solving every sudoku that exists out there.
It’s quite possible that your puzzle requires more advanced strategies
(unless there is a mistake in the numbers you entered). If you do happen
to know what strategies were used to solve this puzzle I am interested
just to learn more - although I am not updating this code add anymore.

On February 8, 2022, ***@***.***> wrote:
> Or there's maybe some another problem. Try this:
>
> var board = [ , ,3,6, ,5,7, , , , , ,9, ,1, , , ,7, , , , , , , ,4
> ,9,6, , , , , ,8,3 , , , , , , , , , ,4,8, , , , , ,1,9 ,6, , , , , ,
> , ,5 , , , ,5, ,7, , , , , ,2,1, ,6,9, ,undefined ]
> Your solver cannot solve it but other solvers yes. I don't know why.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pocketjoso/sudokuJS/issues/6#issuecomment-
1032330643>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABW4CAESTHGAIF5FA2R22BDU2DGXBANCNFSM5NYXI2TQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by vsevjednom-cz** [comment]
I don't know what strategy to use. I can't solve it.
But this page can solve it: https://sudokus.cz/sudoku-x-resitel/

> I am not updating this code add anymore.

😨 😰 😥

**Comment by vsevjednom-cz** [comment]
This Javascript at Github can solve it: http://htmlpreview.github.io/?https://github.com/robatron/sudoku.js/blob/master/demo/index.html
Here is input: `..36.57.....9.1...7.......496.....83.........48.....196.......5...5.7.....21.69..`

**Comment by pocketjoso** [comment]
I see. Looking at their code they are just bruteforcing the sudoku - i.e. trying every possible combination until they find a valid one. That's a completely different approach than this library, which is built to mimic humans in that it attempts strategies in order from easiest to most difficult, in each step.

**Comment by vsevjednom-cz** [comment]
> which is built to mimic humans in that it attempts strategies in order from easiest to most difficult, in each step.

You're right. Your code is more amazing 🥳.
